### ISSUE TITLE
Getting Error HTTP Response Not OK

### ISSUE THREAD

**Issue by uyito** [square/square-java-sdk#92]
**Describe the bug**
I keep getting HTTP Response Not OK whenever I try to create a payment. and the error HTTP Response Not OK doesn't explain what the real issue is. and its very hard to figure this out can you help?

**Expected behavior**
have the sdk return a proper response to show whats is wrong with code. or return what caused the issue.

**Square SDK version**
26.0.0.20221116

**Additional context**
pls provide any context on what might be causing this.

**Comment by havenwood** [comment]
Thank you for the feedback!! I've passed this along to our API team as a request for more fine grained errors that we can expose via the SDK. Closing this issue here since we need to resolve it upstream, but we'd be interested in discussing the failure information that would be most helpful further on [BuildWithSquare Slack](https://squ.re/slack) so we can pass on the feedback.
